version: '3.9'

services:
  
  redis:
    image: redis
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data      
    networks:
      - chat-network

  nginx:
    image: nginx:latest
    container_name: chat-nginx
    working_dir: /var/www/
    ports:
      - "8081:8081"
    volumes:
      - ./../../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
    networks:
      - chat-network
    depends_on:
      - chat-app1
      - chat-app2

  chat-app1:
    image: chat-app1
    container_name: chat-app1
    ports:
      - "5001:5001"
    env_file: .env
    environment:
      - APP_PORT=5001
      - REDIS_URL=redis://redis
      - TOKEN_LIFETIME=86400
    build:
      context: ./../../
      dockerfile: ./docker/demo/.dockerfile
    volumes:
      - ./../../:/var/www      
    working_dir: /var/www/
    networks:
      - chat-network
    depends_on:
      - redis

  chat-app2:
    image: chat-app2
    container_name: chat-app2
    ports:
      - "5002:5002"
    env_file: .env
    environment:
      - APP_PORT=5002
      - REDIS_URL=redis://redis
      - TOKEN_LIFETIME=86400
    build:
      context: ./../../
      dockerfile: ./docker/demo/.dockerfile
    volumes:
      - ./../../:/var/www      
    working_dir: /var/www/
    networks:
      - chat-network
    depends_on:
      - redis

networks:
  chat-network:
    driver: bridge
